In [0]:
#Description: This program detects whether the mail is spam(1) or not spam(0)

In [0]:
#Import Libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [0]:
#Load the data
from google.colab import files
uploaded = files.upload()

Saving emails.csv to emails.csv


In [17]:
#Read the CSV file
df = pd.read_csv("emails.csv")
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [18]:
#Print shape
df.shape

(5728, 2)

In [19]:
#Get the column
df.columns

Index(['text', 'spam'], dtype='object')

In [0]:
#Check for duplicates
df.drop_duplicates(inplace=True)

In [21]:
#Show the new shape 
df.shape

(5695, 2)

In [22]:
#Missing data for each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [23]:
#Download the stopwords package
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [0]:
def process_text(text):
  #1 remove the punctuation 
  #2 remove stopwords
  #3 return a list of clean text 

  #1
  nopunc=[char for char in text if char not in string.punctuation]
  nopunc=''.join(nopunc)

  #2
  clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  #3
  return clean_words

In [25]:
#Tokenization(a list of tokens also called lemmas)
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [0]:
#convert a collection of text to matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [0]:
#split the data into train and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(messages_bow, df['spam'], test_size=0.20, random_state=0)

In [29]:
#Check the shape
messages_bow.shape

(5695, 37229)

In [0]:
#Create and train the Naive Bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(X_train, y_train)

In [31]:
#print the predictions
print(classifier.predict(X_train))

#Print the actual values
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [35]:
#Evaluate the model on the train dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred=classifier.predict(X_train)
print(classification_report(y_train, pred))
print("--------------------------------------")
print("Confusion Matrix: \n", confusion_matrix(y_train, pred))
print("--------------------------------------")
print("Accuracy Score: ", accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556

--------------------------------------
Confusion Matrix: 
 [[3445   12]
 [   1 1098]]
--------------------------------------
Accuracy Score:  0.9971466198419666


In [37]:
print(classifier.predict(X_test))
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [38]:
pred=classifier.predict(X_test)
print(classification_report(y_test, pred))
print("--------------------------------------")
print("Confusion Matrix: \n", confusion_matrix(y_test, pred))
print("--------------------------------------")
print("Accuracy Score: ", accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139

--------------------------------------
Confusion Matrix: 
 [[862   8]
 [  1 268]]
--------------------------------------
Accuracy Score:  0.9920983318700615
